// frontend-vue/components/AbbrItem.vue
<template>
  <tr class="border-b border-gray-200">
    <td class="text-center py-2">
      {{ name }}
    </td>
    <td class="pl-2">
      {{ description }}
    </td>
  </tr>  
</template>

<script>
export default {
  name: "AbbrItem",
  props: {
    name: String,
    description: String,
  },
  computed: {
  }
}
</script>

// frontend/src/components/AbbrItem.tsx
import { IData } from "./AbbrList";

const AbbrItem: React.FC<{ data: IData }> = ({ data }) => {
  const { name, description } = data;
  return (
    <tr className="border-b border-gray-200">
      <td className="text-center py-2">{name}</td>
      <td className="pl-2">{description}</td>
    </tr>
  );
};

export default AbbrItem;
