// frontend/src/components/AbbrList.tsx
type Data = {
  id: number
  name: string
  description: string
}

const AbbrItem: React.FC<{ data: Data }> = ({ data }) => {
  const { name, description } = data
  return (
    <tr className="border-b border-gray-200">
      <td className="text-center py-2">{name}</td>
      <td className="pl-2">{description}</td>
    </tr>
  )
}

const AbbrList: React.FC<{ query: string; data: Data[] }> = ({ query, data }) => {
  const searchResult = () => {
    let result: Data[] = []

    if (query.length < 1) {
      return []
    }

    result.push(
      ...data.filter((item) => {
        return item.name.toLowerCase() === query
      })
    )
    result.push(
      ...data.filter((item) => {
        return item.name.toLowerCase().startsWith(query)
      })
    )
    result.push(
      ...data.filter((item) => {
        return item.name.toLowerCase().includes(query)
      })
    )

    if (query.length > 2) {
      result.push(
        ...data.filter((item) => {
          return item.description.toLowerCase().includes(query)
        })
      )
    }
    return [...new Set(result)]
  }

  return (
    <div className="flex flex-col justify-center mx-2 sm:mx-6">
      <table className="table-auto mb-6">
        <thead>
          <tr className="border-b-2 border-gray-300">
            <th className="font-bold w-1/4">Abbr</th>
            <th className="font-bold w-3/4 text-left pl-2">Description</th>
          </tr>
        </thead>
        <tbody>
          {searchResult().map((row) => {
            return <AbbrItem key={row.id} data={row} />
          })}
        </tbody>
      </table>
    </div>
  )
}

export default AbbrList

// frontend/components/AbbrList.vue
<template>
  <div class="flex flex-col justify-center mx-2 sm:mx-6">    
    <div class="my-3">
      <form v-on:submit.prevent>
        <!-- <label for="search" class="text-center text-xl mb-1 mr-2">
          Search
        </label> -->

        <div class="flex items-center justify-between relative">
          <input
            id="searchInput"
            v-model="query"
            type="text"
            placeholder="Search abbreviations"
            class="pl-6 pr-24 py-2 rounded-lg w-full border border-gray-300 focus:border-gray-800 bg-gray-100 focus:outline-none"
            autofocus
          />

          <div class="absolute inset-y-1 right-0 flex items-center">
            <div
              v-if="query.length > 0"
              class="absolute inset-y-0 right-4 flex items-center"
            >
              <button
                @click="clearInput"
                class="h-full px-3 text-gray-500 hover:text-gray-800"
              >
                <svg
                  class="w-6 h-6"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M6 18L18 6M6 6l12 12"
                  ></path>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </form>
    </div>
    
    <table v-if="filteredAbbrData.length > 0" class="table-auto mb-6">
      <thead>
        <tr class="border-b-2 border-gray-300">
          <th class="font-bold">Abbr</th>
          <th class="font-bold text-left pl-2">Description</th>
          <!-- <th class="font-bold">Wiki</th> -->
        </tr>
      </thead>
      <tbody>
        <AbbrItem
          v-for="abbr in filteredAbbrData"
          v-bind="abbr"
          :key="abbr.id"
        />
      </tbody>
    </table>
    
  </div>
</template>

<script>
import AbbrItem from './AbbrItem'

export default {
  name: 'AbbrList',
  data() {
    return {
      query: '',
    }
  },
  components: {
    AbbrItem,
  },
  props: {
    abbrData: Array,
  },
  methods: {
    clearInput() {
      this.query = ''
      document.querySelector('#searchInput').focus()
    },
  },
  computed: {
    filteredAbbrData() {
      const query = this.query.toLowerCase().trim()
      if (query.length < 1) {
        return []
      }
      return this.abbrData.filter((item) => {
        return (item.name.toLowerCase().includes(query) ||item.description.toLowerCase().includes(query))
      })
    }
  },
}
</script>
